$(document).ready(function(){$('#menu-toggle').click(function(){$(this).toggleClass('open');if($('body').hasClass('no-scroll')){$('body').removeClass('no-scroll');}else{$('body').addClass('no-scroll');}});$('.nav-container .background').click(function(){$('body').find('#menu-toggle').trigger("click");});$("#menu-close").click(function(e){e.preventDefault();$("#sidebar-wrapper, .nav-main").toggleClass("active");$(".nav-main .background").fadeToggle();});$("#menu-toggle").click(function(e){e.preventDefault();$("#sidebar-wrapper, .nav-main").toggleClass("active");$(".nav-main .background").fadeToggle();});var previousTop=0;var offset=3;var navHeight=$('nav').outerHeight();var topBarHeight=$('.top-bar').outerHeight();$(window).bind('scroll',function(){var currentTop=$(window).scrollTop();var navHeight=$('nav').height();if($('.top-bar').length){if(currentTop>topBarHeight&&currentTop<this.previousTop){console.log('1');$('body').addClass('nav-active').removeClass('nav-inactive');}else if(currentTop>topBarHeight&&currentTop>this.previousTop){console.log('2');$('body').addClass('nav-inactive').removeClass('nav-active');}else if(currentTop<=topBarHeight&&currentTop<this.previousTop){console.log('3');$('body').removeClass('nav-active').removeClass('nav-inactive');}}
if($(window).scrollTop()>offset){$('body').addClass('on');}else{$('body').removeClass('on');}
this.previousTop=currentTop;});$('a.page-scroll').bind('click',function(event){var $anchor=$(this);$('html, body').stop().animate({scrollTop:($($anchor.attr('href')).offset().top-50)},1250,'easeInOutExpo');event.preventDefault();});$('body').scrollspy({target:'.navbar-default',offset:80})
function markLinks(){var $links=$('.flex-active-slide .flx-reveal');$links.each(function(i){var $this=$(this);$this.delay(i*350).queue(function(){$this.addClass('flx-reveal-visible').dequeue();});});}
$('#index-slider').flexslider({animation:"fade",slideshowSpeed:5000,pauseOnHover:true,controlNav:true,smoothHeight:false,directionNav:true,});var duration=1000;$('.scroll-down').click(function(e){e.preventDefault();$("html, body").animate({"scrollTop":$('section#intro').offset().top},duration,'easeInOutExpo');});$('.slider .tagline-wrapper').css("width",$(window).width());$(window).resize(function(){$('.slider .tagline-wrapper').css("width",$(window).width());});$('#events').owlCarousel({loop:true,margin:20,smartSpeed:800,autoplay:true,dots:false,navText:false,nav:true,navigation:false,center:true,responsive:{0:{items:1},600:{items:1},1000:{items:2}}});var tabCarousel;$('#home .panel').hover(function(ev){clearInterval(tabCarousel);},function(ev){tabCarousel=setInterval(function(){var tabs=$('.panel-body .nav-tabs > li'),active=tabs.filter('.active'),next=active.next('li'),toClick=next.length?next.find('a'):tabs.eq(0).find('a');toClick.trigger('click');},5000);});$(".share").on('click',function(e){if(e.target!=this)return;$('.share, .fab').toggleClass("active");});$(".share, .share i").hover(function(e){$('.share, .fab').addClass("active");},function(){$('.share, .fab').removeClass("active");});(function(){var d=document,accordionToggles=d.querySelectorAll('.js-accordionTrigger'),setAria,setAccordionAria,switchAccordion,touchSupported=('ontouchstart'in window),pointerSupported=('pointerdown'in window);skipClickDelay=function(e){e.preventDefault();e.target.click();}
setAriaAttr=function(el,ariaType,newProperty){el.setAttribute(ariaType,newProperty);};setAccordionAria=function(el1,el2,expanded){switch(expanded){case"true":setAriaAttr(el1,'aria-expanded','true');setAriaAttr(el2,'aria-hidden','false');break;case"false":setAriaAttr(el1,'aria-expanded','false');setAriaAttr(el2,'aria-hidden','true');break;default:break;}};switchAccordion=function(e){console.log("triggered");e.preventDefault();var thisAnswer=e.target.parentNode.nextElementSibling;var thisQuestion=e.target;if(thisAnswer.classList.contains('is-collapsed')){setAccordionAria(thisQuestion,thisAnswer,'true');}else{setAccordionAria(thisQuestion,thisAnswer,'false');}
thisQuestion.classList.toggle('is-collapsed');thisQuestion.classList.toggle('is-expanded');thisAnswer.classList.toggle('is-collapsed');thisAnswer.classList.toggle('is-expanded');thisAnswer.classList.toggle('animateIn');};for(var i=0,len=accordionToggles.length;i<len;i++){if(touchSupported){accordionToggles[i].addEventListener('touchstart',skipClickDelay,false);}
if(pointerSupported){accordionToggles[i].addEventListener('pointerdown',skipClickDelay,false);}
accordionToggles[i].addEventListener('click',switchAccordion,false);}})();$('.menu-item-has-children').hover(function(){clearTimeout($.data(this,'timer'));$(this).addClass('active');$(this).children(".sub-menu").stop(true,true).slideDown(200);},function(){$.data(this,'timer',setTimeout($.proxy(function(){$(this).children(".sub-menu").stop(true,true).slideUp(350,'easeInOutExpo');$(this).removeClass('active');},this),200));});if(($(".promo-bar").hasClass("visible"))){setTimeout(function(){$(".promo-bar").removeClass('visible');},4000);}
$(document).on('click','.promo-trigger, .promo-bar, .promo-btn',function(e){e.preventDefault();if(($(".promo-box").hasClass("visible"))){$(".promo-box").removeClass('visible');$(".promo-bar").addClass('visible');setTimeout(function(){$(".promo-bar").removeClass('visible');},4000);}else{$(".promo-box").addClass('visible');$(".promo-bar").removeClass('visible');}});if($(window).width()<767){$("ul.dropdown").on("click",".init",function(){$("ul.dropdown").children('li:not(.init)').hide();$(this).closest("ul").children('li:not(.init)').toggle();});$("ul.dropdown").on("click","li:not(.init)",function(){$(this).closest("ul").children('.init').html($(this).text());$(this).closest("ul").children('li:not(.init)').hide();});}else{$("ul.dropdown").children('li:not(.init)').show().removeAttr('style');$("ul.dropdown").on("click",".init",function(){$("ul.dropdown").children('li:not(.init)').show().removeAttr('style');$(this).closest("ul").children('li:not(.init)').toggle();});$("ul.dropdown").on("click","li:not(.init)",function(){$(this).closest("ul").children('.init').html($(this).text());$(this).closest("ul").children('li:not(.init)').show().removeAttr('style');});}
$('.disabled').click(function(e){e.preventDefault();})
leaf_mobile_menu();}());function leaf_mobile_menu(){var $menu=$("#primary-menu").clone();$menu.find("ul").removeClass("menu");$menu.find("ul").removeAttr("style");$menu.find("li").removeAttr("style");$menu.find("li").each(function(){if($(this).find('> ul').length>0){$(this).prepend('<span class="sf-sub-indicator"></span>');}})
$(".container > #primary-menu").after("<div id='mobile-menu' class='navbar-collapse collapse navbar-right'>"+$menu.html()+"</div>");$('#mobile-menu-trigger').click(function(){$('#mobile-menu').stop(true,true).slideToggle(200);return false;});$('#mobile-menu .container ul li ul').hide();$('#mobile-menu .sf-sub-indicator').click(function(){$(this).parent().toggleClass('open');$(this).parent().find('> ul').stop(true,true).slideToggle(200);return false;});}
if($('.grid').length){$('.grid').isotope({itemSelector:'.grid-item',percentPosition:true,masonry:{columnWidth:1}});$('.grid').imagesLoaded(function(){$('.grid').isotope({itemSelector:'.grid-item',percentPosition:true,masonry:{columnWidth:1}});$('.grid').isotope('reLayout');});}
$('.photo-gallery').magnificPopup({delegate:'a',type:'image',mainClass:'mfp-fade',removalDelay:180,gallery:{enabled:true}});$(document).ready(function(){if($('.image-link').length){$('.image-link').magnificPopup({type:'image',mainClass:'mfp-fade',removalDelay:180,preloader:false,});}
if($('.popup-youtube').length){$('.popup-youtube').magnificPopup({disableOn:100,type:'iframe',mainClass:'mfp-fade',removalDelay:180,preloader:false,fixedContentPos:false});}
if($('.popup-chope').length){$('.popup-chope').magnificPopup({disableOn:100,type:'iframe',mainClass:'mfp-fade',removalDelay:180,preloader:false,fixedContentPos:true});}
if($('.popup-modal').length){$('.popup-modal').magnificPopup({type:'inline',preloader:false,mainClass:'mfp-fade',removalDelay:180,modal:true});}
$('.popup-with-zoom-anim').magnificPopup({type:'inline',fixedContentPos:true,fixedBgPos:true,closeBtnInside:true,preloader:false,midClick:true,removalDelay:300,mainClass:'my-mfp-zoom-in'});$(document).on('click','.mfp-close',function(e){e.preventDefault();$.magnificPopup.close();});});var rafId=null;var delay=200;var lTime=0;function scroll(){var scrollTop=$(window).scrollTop();var height=$(window).height()
var visibleTop=scrollTop+height;$('.reveal').each(function(){var $t=$(this);if($t.hasClass('reveal_visible')){return;}
var top=$t.offset().top;if(top<=visibleTop){if(top<scrollTop){$t.removeClass('reveal_pending').addClass('reveal_visible');}else{$t.addClass('reveal_pending');if(!rafId)requestAnimationFrame(reveal);}}});}
function reveal(){rafId=null;var now=performance.now();if(now-lTime>delay){lTime=now;var $ts=$('.reveal_pending');$($ts.get(0)).removeClass('reveal_pending').addClass('reveal_visible');}
if($('.reveal_pending').length>=1)rafId=requestAnimationFrame(reveal);}
$(scroll);$(window).scroll(scroll);$(window).load(function(){if($('.grid-project').length){$('.grid-project').isotope({itemSelector:'.grid-project-item',percentPosition:true,masonry:{gutter:10}});}
if($('.grid-menu').length){var $container=$('.grid-menu'),filters={};var $grid=$('.grid-menu').isotope({itemSelector:'.grid-menu-item',percentPosition:true,getSortData:{fileby:'.file-by',filename:'.file-name',filedate:'[data-ticks]',filesize:function(itemElem){var filesize=$(itemElem).attr('data-filesize');return parseInt(filesize);}},masonry:{columnWidth:'.grid-sizer'}});$('.filter-button').on('click','a',function(){event.preventDefault();var $this=$(this);if($this.hasClass('selected')){return;}
var $optionSet=$this.parents('.option-set');$optionSet.find('.selected').removeClass('selected');$this.addClass('selected');var group=$optionSet.attr('data-filter-group');filters[group]=$this.attr('data-filter-value');var isoFilters=[];for(var prop in filters){isoFilters.push(filters[prop])}
var selector=isoFilters.join('');$container.isotope({filter:selector});});}})
$(window).resize(function(){if($(window).width()<767){$("ul.dropdown").on("click",".init",function(){$("ul.dropdown").children('li:not(.init)').hide();$(this).closest("ul").children('li:not(.init)').toggle();});$("ul.dropdown").on("click","li:not(.init)",function(){$(this).closest("ul").children('.init').html($(this).text());$(this).closest("ul").children('li:not(.init)').hide();});}else{$("ul.dropdown").children('li:not(.init)').show().removeAttr('style');$("ul.dropdown").on("click",".init",function(){$("ul.dropdown").children('li:not(.init)').show().removeAttr('style');$(this).closest("ul").children('li:not(.init)').toggle();});$("ul.dropdown").on("click","li:not(.init)",function(){$(this).closest("ul").children('.init').html($(this).text());$(this).closest("ul").children('li:not(.init)').show().removeAttr('style');});}});